---
sidebar: sidebar 
permalink: concept-write-speed.html 
keywords: write speed, high write speed, normal write speed, nvfail, writing speed, ldm, low durability mode 
summary: NetApp Console讓您能夠為Cloud Volumes ONTAP選擇正常或高寫入速度。在選擇寫入速度之前，您應該了解正常設定和高設定之間的差異以及使用高寫入速度時的風險和建議。 
---
= 寫入速度
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console可讓您為大多數Cloud Volumes ONTAP設定選擇正常或高寫入速度。在選擇寫入速度之前，您應該了解正常設定和高設定之間的差異以及使用高寫入速度時的風險和建議。



== 正常寫入速度

當您選擇正常寫入速度時，資料將直接寫入磁碟。當資料直接寫入磁碟時，可以降低發生意外系統中斷或涉及意外系統中斷的級聯故障（僅限 HA 對）時資料遺失的可能性。

正常寫入速度是預設選項。



== 高寫入速度

當您選擇高寫入速度時，資料會在寫入磁碟之前緩衝在記憶體中，從而提供更快的寫入效能。由於這種緩存，如果發生意外的系統中斷，則可能會遺失資料。

發生意外系統中斷時可能遺失的資料量是最後兩個一致點的跨度。一致點是將緩衝資料寫入磁碟的行為。當寫入日誌已滿或 10 秒後（以先到者為準）就會出現一致點。但是，雲端提供者提供的儲存效能可能會影響一致點處理時間。



=== 何時使用高寫入速度

如果您的工作負載需要快速寫入效能，並且您可以承受意外系統中斷或涉及意外系統中斷的級聯故障（僅限 HA 對）時資料遺失的風險，那麼高寫入速度是一個不錯的選擇。



=== 使用高寫入速度時的建議

如果啟用高寫入速度，則應確保應用程式層的寫入保護，或確保應用程式能夠容忍資料遺失（如果發生）。

ifdef::aws[]



=== AWS 中的 HA 對具有高寫入速度

如果您打算在 AWS 中的 HA 對上啟用高寫入速度，則應了解多可用區 (AZ) 部署和單一可用區部署之間的保護等級差異。跨多個可用區部署 HA 對可提供更高的彈性，並有助於降低資料遺失的可能性。

link:concept-ha.html["了解有關 AWS 中的 HA 對的更多信息"] 。

endif::aws[]



=== 支援高寫入速度的配置

並非所有Cloud Volumes ONTAP配置都支援高寫入速度。這些配置預設使用正常的寫入速度。

ifdef::aws[]



==== AWS

如果您使用單節點系統， Cloud Volumes ONTAP支援所有執行個體類型的高寫入速度。

從 9.8 版本開始， Cloud Volumes ONTAP在使用幾乎所有受支援的 EC2 執行個體類型（m5.xlarge 和 r5.xlarge 除外）時都支援具有 HA 對的高寫入速度。

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-aws.html["了解有關Cloud Volumes ONTAP支援的 Amazon EC2 執行個體的更多信息"^] 。

endif::aws[]

ifdef::azure[]



==== Azure

如果您使用單節點系統， Cloud Volumes ONTAP支援所有 VM 類型的高寫入速度。

如果您使用 HA 對，從 9.8 版本開始， Cloud Volumes ONTAP支援多種 VM 類型的高寫入速度。前往 https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Cloud Volumes ONTAP發行說明"^]查看支援高寫入速度的虛擬機器類型。

endif::azure[]

ifdef::gcp[]



==== Google雲

如果您使用單節點系統， Cloud Volumes ONTAP支援所有機器類型的高寫入速度。

如果您使用 HA 對，從 9.13.0 版本開始， Cloud Volumes ONTAP支援多種 VM 類型的高寫入速度。前往 https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html#supported-configurations-by-license["Cloud Volumes ONTAP發行說明"^]查看支援高寫入速度的虛擬機器類型。

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["詳細了解Cloud Volumes ONTAP支援的 Google Cloud 機器類型"^] 。

endif::gcp[]



== 如何選擇寫入速度

您可以在新增的Cloud Volumes ONTAP系統時選擇寫入速度，並且可以link:task-modify-write-speed.html["更改現有系統的寫入速度"]。



== 如果發生資料遺失會發生什麼

如果因寫入速度過快而導致資料遺失，事件管理系統 (EMS) 會報告以下兩個事件：

* Cloud Volumes ONTAP 9.12.1 或更高版本
+
 NOTICE nv.data.loss.possible: An unexpected shutdown occurred while in high write speed mode, which possibly caused a loss of data.
* Cloud Volumes ONTAP 9.11.0 至 9.11.1
+
 DEBUG nv.check.failed: NVRAM check failed with error "NVRAM disabled due to dirty shutdown with High Write Speed mode"
+
 ERROR wafl.root.content.changed: Contents of the root volume '' might have changed. Verify that all recent configuration changes are still in effect..
* Cloud Volumes ONTAP 9.8 至 9.10.1
+
 DEBUG nv.check.failed: NVRAM check failed with error "NVRAM disabled due to dirty shutdown"
+
 ERROR wafl.root.content.changed: Contents of the root volume '' might have changed. Verify that all recent configuration changes are still in effect.


當這種情況發生時， Cloud Volumes ONTAP應該能夠啟動並繼續提供數據，而無需使用者乾預。



== 如果發生資料遺失，如何停止資料存取

如果您擔心資料遺失，希望應用程式在資料遺失時停止運行，並在正確解決資料遺失問題後恢復資料訪問，則可以使用 CLI 中的 NVFAIL 選項來實現該目標。

啟用 NVFAIL 選項:: `vol modify -volume <vol-name> -nvfail on`
檢查 NVFAIL 設定:: `vol show -volume <vol-name> -fields nvfail`
停用 NVFAIL 選項:: `vol modify -volume <vol-name> -nvfail off`


當發生資料遺失時，啟用 NVFAIL 的 NFS 或 iSCSI 磁碟區應停止提供資料（這對無狀態協定 CIFS 沒有影響）。有關詳細信息，請參閱 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-mgmt-dr/GUID-40D04B8A-01F7-4E87-8161-E30BD80F5B7F.html["NVFAIL 如何影響對 NFS 卷或 LUN 的訪問"^]。

檢查 NVFAIL 狀態:: `vol show -fields in-nvfailed-state`


正確解決資料遺失問題後，您可以清除 NVFAIL 狀態，然後磁碟區將可供資料存取。

清除 NVFAIL 狀態:: `vol modify -volume <vol-name> -in-nvfailed-state false`

