---
sidebar: sidebar 
permalink: concept-storage-management.html 
keywords: provisioning, capacity management, storage provisioning, manual, automatic, advanced allocation, aggregates, thin provisioning, free space, mode, BlueXP, NetApp Consolecloud manager 
summary: 該控制台提供了Cloud Volumes ONTAP儲存的簡化和高階管理。 
---
= Cloud Volumes ONTAP儲存管理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp控制台提供了對Cloud Volumes ONTAP儲存的簡化和進階管理。


CAUTION: 您必須直接從控制台建立和刪除所有磁碟和聚合。您不應從其他管理工具執行這些操作。這樣做會影響系統穩定性，妨礙將來添加磁碟的能力，並可能產生冗餘的雲端供應商費用。



== 儲存配置

控制台透過為您購買磁碟和管理聚合，使Cloud Volumes ONTAP 的儲存配置變得簡單。您只需要建立磁碟區。如果您願意，您可以使用進階分配選項自行配置聚合。



=== 簡化配置

聚合為磁碟區提供雲端儲存。當您啟動執行個體以及配置其他磁碟區時，控制台會為您建立聚合。

建立磁碟區時，控制台會執行以下三件事之一：

* 它將磁碟區放置在具有足夠可用空間的現有聚合上。
* 它透過為聚合購買更多磁碟將磁碟區放置在現有聚合上。


ifdef::aws[]

+ 在支援彈性磁碟區的 AWS 聚合的情況下，它也會增加 RAID 群組中磁碟的大小。link:concept-aws-elastic-volumes.html["了解有關彈性卷支持的更多信息"] 。

endif::aws[]

* 它為新聚合購買磁碟並將磁碟區放置在該聚合上。


控制台透過查看幾個因素來確定新磁碟區的放置位置：聚合的最大大小、是否啟用精簡配置以及聚合的可用空間閾值。

ifdef::aws[]



==== AWS 中聚合的磁碟大小選擇

當控制台在 AWS 中為Cloud Volumes ONTAP建立新聚合時，它會隨著聚合數量的增加而逐漸增加磁碟大小，以在達到 AWS 資料磁碟限制之前最大化系統容量。

例如，控制台可能會選擇以下磁碟大小：

[cols="3*"]
|===
| 總數 | 磁碟大小 | 最大總容量 


| 1 | 500 GiB | 3 TiB 


| 4 | 1 TiB | 6 TiB 


| 6 | 2 TiB | 12 TiB 
|===

NOTE: 此行為不適用於支援 Amazon EBS 彈性磁碟區功能的聚合。啟用了彈性卷的聚合由一個或兩個 RAID 群組組成。每個 RAID 群組有四個相同的磁碟，容量相同。link:concept-aws-elastic-volumes.html["了解有關彈性卷支持的更多信息"] 。

您可以使用進階分配選項自行選擇磁碟大小。

endif::aws[]



=== 進階分配

您也可以管理聚合。link:task-create-aggregates.html["從「進階分配」頁面"] ，您可以建立包含特定數量磁碟的新聚合、將磁碟新增至現有聚合以及在特定聚合中建立磁碟區。



== 容量管理

組織或帳戶管理員可以設定控制台來通知您儲存容量決策或是否自動為您管理容量需求。

此行為由控制台代理程式上的_容量管理模式_決定。容量管理模式會影響此控制台代理管理的所有Cloud Volumes ONTAP系統。如果您有另一個控制台代理，則可以進行不同的配置。



=== 自動容量管理

容量管理模式預設為自動。在此模式下，控制台每 15 分鐘檢查一次可用空間比率，以確定可用空間比率是否低於指定的閾值。如果需要更多容量，它會啟動購買新磁碟、刪除未使用的磁碟集合（聚合）、根據需要在聚合之間移動卷，並嘗試防止磁碟故障。

以下範例說明了此模式的工作原理：

* 如果聚合達到容量閾值並且有空間容納更多磁碟，則控制台會自動為該聚合購買新磁碟，以便磁碟區可以繼續成長。
+
ifdef::aws[]



對於支援彈性磁碟區的 AWS 中的聚合，它還會增加 RAID 群組中磁碟的大小。link:concept-aws-elastic-volumes.html["了解有關彈性卷支持的更多信息"] 。

endif::aws[]

+ * 如果聚合達到容量閾值且無法支援任何額外的磁碟，則控制台會自動將磁碟區從該聚合移至具有可用容量的聚合或新的聚合。

+ 如果控制台為磁碟區建立新的聚合，它會選擇適合該磁碟區大小的磁碟大小。

+ 請注意，原始聚合上現在有可用空間。現有磁碟區或新磁碟區可以使用該空間。在這種情況下，空間無法返回給雲端提供者。

* 如果聚合中超過 12 小時沒有捲，控制台就會將其刪除。




==== 使用自動容量管理來管理 LUN

控制台的自動容量管理不適用於 LUN。當它建立 LUN 時，它會停用自動增長功能。



=== 手動容量管理

如果組織或帳戶管理員將容量管理模式設為手動，控制台會通知您採取適當的措施來做出容量決策。自動模式中所述的相同範例也適用於手動模式，但是否接受操作取決於您。



=== 了解更多

link:task-manage-capacity-settings.html["了解如何修改容量管理模式"] 。
