---
sidebar: sidebar 
permalink: concept-licensing-charging.html 
keywords: capacity-based license charging, consumption for licenses, pricing for licenses, CVO licensing, CVO charging, SnapLock charging, CIFS charging, audit volumes, primary volumes, volume-based charging 
summary: 熟悉基於容量的許可證的收費、消費模式、定價和配置。 
---
= 了解有關Cloud Volumes ONTAP基於容量的許可證的更多信息
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您應該熟悉基於容量的許可證的收費方式和容量使用。



== 消費模式或許可購買選項

我們提供基於容量的授權套餐，並有以下幾種消費模式或購買選項：

* *BYOL*：自備授權（BYOL）。從NetApp購買的許可證，可用於在任何雲端供應商中部署Cloud Volumes ONTAP 。
+

NOTE: 已限制 BYOL 授權的購買、延期和續約。有關更多信息，請參閱 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html#restricted-availability-of-byol-licensing-for-cloud-volumes-ontap["Cloud Volumes ONTAP的 BYOL 授權可用性受限"^] 。



ifdef::azure[]

endif::azure[]

* *PAYGO*：即用即付 (PAYGO) 訂閱是從雲端供應商市場按小時訂閱的。
* *年度*：來自雲端提供者市場的年度合約。


請注意以下事項：

* 如果您從NetApp購買了 BYOL 許可證，則還需要從雲端供應商的雲端市場訂閱 PAYGO 產品。 NetApp已限制 BYOL 授權。當您的 BYOL 授權到期時，您需要將其替換為雲端市場訂閱。
+
您的許可證總是會先被收費，但在以下情況下，我們將按照市場上的小時費率向您收費：

+
** 如果您超出許可容量
** 如果您的許可證期限已到期


* 如果您與市場簽訂了年度合同，則您部署的所有Cloud Volumes ONTAP系統都將根據該合約收費。您不能將年度市場合約與 BYOL 混合搭配。
* 中國區域僅支援支援 BYOL 的單節點系統。中國區域部署不受 BYOL 授權限制。




== 更改許可證包

部署後，您可以變更使用基於容量的許可的Cloud Volumes ONTAP系統的軟體包。例如，如果您使用 Essentials 套件部署了Cloud Volumes ONTAP系統，則可以在業務需求變更時將其變更為 Professional 套件。

link:task-manage-capacity-licenses.html["了解如何更改充電方式"] 。

有關將基於節點的許可證轉換為基於容量的許可證的信息，請參閱



== 支援的儲存類型和套餐如何收費

Cloud Volumes ONTAP的計費是基於多種因素，例如套餐和卷類型。Cloud Volumes ONTAP 9.7 及更高版本提供基於容量的授權包。

有關定價的詳細信息，請訪問 https://bluexp.netapp.com/pricing/["NetApp Console網站"^]。



=== 儲存虛擬機

* 額外的資料服務儲存虛擬機器 (SVM) 無需額外的授權費用，但每個資料服務 SVM 至少需支付 4 TiB 的容量費用。
* 災難復原 SVM 根據預置容量收費。




=== HA 對

對於 HA 對，您只需為節點上配置的容量付費。您無需為同步鏡像到合作夥伴節點的資料付費。



=== FlexClone和FlexCache卷

* 您無需為FlexClone磁碟區所使用的容量付費。
* 來源和目標FlexCache磁碟區被視為主數據，並根據配置的空間收費。




=== 讀/寫卷

如果您建立或使用可寫入（讀取/寫入）卷，則該磁碟區將被視為主卷，並按每個儲存虛擬機器 (SVM) 的最低費用收取已配置容量的費用。例如FlexVol讀/寫卷、 SnapLock審計捲和 CIFS/NFS 審計卷。所有用戶創建的數據量均按您的訂閱和套餐類型收費。  ONTAP內部自動建立且無法儲存資料的磁碟區（例如 SVM 根磁碟區）不收費。



=== 基本套裝

使用 Essentials 套件時，您需要根據部署類型（HA 或單節點）和磁碟區類型（主磁碟區或輔助磁碟區）付費。價格由高至低的順序如下：_Essentials Primary HA_、_Essentials Primary Single Node_、_Essentials Secondary HA_ 和 _Essentials Secondary Single Node_。或者，當您購買市場合約或接受私人優惠時，任何部署或卷類型的容量費用都是相同的。

許可證完全基於Cloud Volumes ONTAP系統內建立的磁碟區類型：

* 基本單節點：僅使用一個ONTAP節點在Cloud Volumes ONTAP系統上建立的讀取/寫入磁碟區。
* Essentials HA：使用兩個ONTAP節點讀取/寫入卷，這兩個節點可以相互故障轉移，以實現無中斷資料存取。
* 基本輔助單節點：僅使用一個ONTAP節點在Cloud Volumes ONTAP系統上建立的資料保護 (DP) 類型磁碟區（通常是唯讀的SnapMirror或SnapVault目標磁碟區）。
+

NOTE: 如果只讀/DP 磁碟區成為主卷，則控制台會將其視為主數據，並且收費成本將根據磁碟區處於讀取/寫入模式的時間來計算。當磁碟區再次變為唯讀/DP 時，它會再次將該磁碟區視為輔助數據，並使用控制台中最匹配的授權進行相應的收費。

* 基本輔助 HA：在Cloud Volumes ONTAP系統上使用兩個可以相互故障轉移以實現無中斷資料存取的ONTAP節點建立的資料保護 (DP) 類型磁碟區（通常是唯讀的SnapMirror或SnapVault目標磁碟區）。




== 容量限制

在基於容量的許可模型中，每個Cloud Volumes ONTAP系統都支援分層到物件存儲，並且總分層容量可以擴展到雲端提供者的存儲桶限制。雖然許可證沒有施加容量限制，但遵循 https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["FabricPool最佳實踐"^]確保在配置和管理分層時實現最佳效能、可靠性和成本效率。

有關每個雲端提供者的容量限制的信息，請參閱其文檔：

* https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketRestrictions.html["AWS 文件"^]
* https://learn.microsoft.com/en-us/azure/storage/common/scalability-targets-standard-account["託管磁碟的 Azure 文件"^]和 https://learn.microsoft.com/en-us/azure/storage/blobs/scalability-targets["Azure Blob 儲存體文檔"^]
* https://cloud.google.com/storage/docs/buckets["Google Cloud 文件"^]




== 最大系統數量

採用基於容量的許可方式，每個NetApp Console組織最多可擁有 24 個Cloud Volumes ONTAP系統。_系統_ 是Cloud Volumes ONTAP HA 對、 Cloud Volumes ONTAP單節點系統或您建立的任何其他儲存虛擬機器。預設儲存虛擬機器不計入限制。此限制適用於所有許可模式。

例如，假設您有三個系統：

* 具有一個儲存虛擬機器的單節點Cloud Volumes ONTAP系統（這是部署Cloud Volumes ONTAP時所建立的預設儲存虛擬機器）
+
該系統算一個系統。

* 具有兩個儲存虛擬機（預設儲存虛擬機，加上您建立的一個額外的儲存虛擬機）的單節點Cloud Volumes ONTAP系統
+
系統算是兩個系統：一個用於單節點系統，一個用於附加儲存 VM。

* 具有三個儲存虛擬機（預設儲存虛擬機，以及您建立的兩個額外的儲存虛擬機）的Cloud Volumes ONTAP HA 對
+
系統計為三個系統：一個用於 HA 對，兩個用於附加儲存虛擬機器。



總共有六個系統。這樣一來，您的組織中就可以再容納 14 個系統。

如果您需要部署超過 24 台系統，請聯絡您的客戶代表或銷售團隊。

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html["了解 AWS、Azure 和 Google Cloud 的儲存限制"^] 。



== 最低收費

對於每個具有至少一個主（讀寫）卷的提供資料的儲存虛擬機，最低收費為 4 TiB。如果主磁碟區的總和小於 4 TiB，則控制台將對該儲存虛擬機器套用 4 TiB 的最低費用。

如果您尚未配置任何卷，則不適用最低費用。

對於 Essentials 包，4 TiB 最低容量費用不適用於僅包含輔助（資料保護）磁碟區的儲存虛擬機器。例如，如果您有一個包含 1 TiB 二級資料的儲存虛擬機，那麼您只需為該 1 TiB 資料付費。對於專業套餐類型，無論卷類型如何，最低容量收費均為 4 TiB。



== 超額費用如何收取

如果您超出了 BYOL 容量，我們將根據您的市場訂閱按小時費率向您收取超額費用。超額部分將按市場費率收費，並優先使用其他許可證中的可用容量。如果您的 BYOL 授權到期，您需要透過雲端市場過渡到基於容量的授權模式。更多資訊請參閱link:task-convert-node-capacity.html["將Cloud Volumes ONTAP基於節點的許可證轉換為基於容量的許可證"]。



=== Essentials許可證超額費用如何收取

如果您從NetApp購買 Essentials 授權（自帶授權），並且超出了特定 Essentials 軟體套件的授權容量，則控制台會將超出部分的費用計入價格較高的 Essentials 授權（如果您有可用容量的授權）。遊戲主機會先使用您已付費的可用容量，然後再向市場收費。如果您的 BYOL 授權沒有可用容量，超出容量的部分將按市場按需小時費率 (PAYGO) 收費，並添加到您的月帳單中。

同樣，如果您簽訂了年度市場合約或包含多個 Essentials 套餐的私人優惠，並且您的使用量超過了特定套餐的部署和容量類型的承諾容量，則控制台會根據可用容量，向價格更高的 Essentials 套餐收取超額費用。當該容量耗盡後，剩餘的超額容量將以市場按需（PAYGO）小時費率計費，並添加到您的月帳單中。

有關 Essentials 許可證收費的信息，請參閱link:concept-licensing-charging.html#essentialscharging["基本套裝"]。

這是一個例子。假設您擁有 Essentials 套件的以下許可證：

* 具有 500 TiB 承諾容量的 500 TiB _Essentials Secondary HA_ 許可證
* 500 TiB 的「Essentials 單節點」許可證，僅具有 100 TiB 的承諾容量


另外 50 TiB 在具有輔助卷的 HA 對上進行配置。控制台不會向 PAYGO 收取這 50 TiB 的費用，而是向 _Essentials Single Node_ 授權收取 50 TiB 的超額費用。該許可證的價格高於_Essentials Secondary HA_，但它利用您已購買的許可證，並且不會增加您的每月帳單費用。

在「管理」> 「Licenses and subscriptions」中，您可以看到針對「Essentials 單節點」許可證收取了 50 TiB 的費用。

這是另一個例子。假設您擁有 Essentials 套件的以下許可證：

* 具有 500 TiB 承諾容量的 500 TiB _Essentials Secondary HA_ 許可證
* 500 TiB 的「Essentials 單節點」許可證，僅具有 100 TiB 的承諾容量


另外 100 TiB 在具有主磁碟區的 HA 對上進行設定。您購買的許可證沒有_Essentials Primary HA_承諾容量。  _Essentials Primary HA_ 授權的價格高於 _Essentials Primary Single Node_ 和 _Essentials Secondary HA_ 授權。

在此範例中，控制台會依照市場價格對額外的 100 TiB 收取超額費用。超額費用將出現在您的每月帳單上。
