---
sidebar: sidebar 
permalink: task-accelerate-data-access.html 
keywords: flexcache, flexcache volumes, create a flexcache volume, provision flexcache, create flexcache volume 
summary: FlexCache卷是一種儲存卷，用於快取來自來源卷或來源卷的 NFS 讀取資料。隨後讀取快取資料可以加快對該資料的存取速度。 
---
= 使用Cloud Volumes ONTAP系統上的FlexCache磁碟區加速資料存取
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
FlexCache卷是一種儲存卷，用於快取從原始（或來源）卷讀取的 SMB 和 NFS 資料。隨後讀取快取資料可以加快對該資料的存取速度。

您可以使用FlexCache磁碟區來加快資料存取速度或卸載存取量大的磁碟區的流量。  FlexCache磁碟區有助於提高效能，特別是當用戶端需要重複存取相同資料時，因為可以直接提供資料而無需存取原始磁碟區。  FlexCache卷非常適合讀取密集的系統工作負載。

NetApp Console 提供FlexCache磁碟區的管理link:https://docs.netapp.com/us-en/bluexp-volume-caching/index.html["NetApp磁碟區快取"^]。

您也可以使用ONTAP CLI 或ONTAP系統管理器來建立和管理FlexCache磁碟區：

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-fc-mgmt/home.html["FlexCache卷實現更快資料存取電源指南"^]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-07F4C213-076D-4FE8-A8E3-410F49498D49.html["在 System Manager 中建立FlexCache卷"^]


video::PBNPVRUeT1o[youtube,width=848,height=480]


== 當來源加密時使用FlexCache

在原始磁碟區已加密的Cloud Volumes ONTAP系統上設定FlexCache時，需要執行額外的步驟，以確保FlexCache磁碟區可以正確存取和快取加密資料。

.開始之前
. *加密設定*：確保來源磁碟區完全加密且可操作。對於Cloud Volumes ONTAP系統，這涉及與特定於雲端的金鑰管理服務整合。


ifdef::aws[]

對於 AWS，這通常表示使用 AWS 金鑰管理服務 (KMS)。有關信息，請參閱link:task-aws-key-management.html["使用 AWS Key Management Service 管理金鑰"]。

endif::aws[]

ifdef::azure[]

對於 Azure，您需要為NetApp磁碟區加密 (NVE) 設定 Azure Key Vault。有關信息，請參閱link:task-azure-key-vault.html["使用 Azure Key Vault 管理金鑰"]。

endif::azure[]

ifdef::gcp[]

對於 Google Cloud，它是 Google Cloud Key Management Service。有關信息，請參閱link:task-google-key-manager.html["使用 Google 的雲端金鑰管理服務管理金鑰"]。

endif::gcp[]

. *金鑰管理服務*：在建立FlexCache區之前，請先確認金鑰管理服務是否在Cloud Volumes ONTAP系統上正確設定。此配置對於FlexCache磁碟區解密來自原始磁碟區的資料至關重要。
. *許可*：確認有效的FlexCache許可證可用並在Cloud Volumes ONTAP系統上啟動。
. * ONTAP版本*：確保您的Cloud Volumes ONTAP系統的ONTAP版本支援帶有加密磁碟區的FlexCache 。參考最新 https://docs.netapp.com/us-en/ontap/release-notes/index.html["ONTAP發行說明"^]或相容性矩陣以獲取更多資訊。
. *網路配置*：確保網路配置允許原始磁碟區和FlexCache磁碟區之間的無縫通訊。這包括雲端環境中的正確路由和 DNS 解析。


.步驟
使用加密來源磁碟區在Cloud Volumes ONTAP系統上建立FlexCache磁碟區。有關詳細步驟和其他注意事項，請參閱以下部分：

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-fc-mgmt/home.html["FlexCache卷實現更快資料存取電源指南"^]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-07F4C213-076D-4FE8-A8E3-410F49498D49.html["在 System Manager 中建立FlexCache卷"^]

