---
sidebar: sidebar 
permalink: task-planning-your-config.html 
keywords: license, disk, ebs, storage, size, write speed, volume usage, ec2, capacity, limit, configurations, virtual machine, vm, regions, supported disks, disk types, general purpose, gp2 provisioned IOPS, piops, throughput optimized, cold, SSD, HDD, st1, use profile, thin provisioning, deduplication, compression, shared instance, dedicated instance, write speed, high write speed, normal write speed, network information, worksheet, limit, limits, storage limits, volume limit, aggregate limit, maximum volume size, maximum aggregate size, supported instances, instances, instances supported, supported ec2 instances, supported instance, aws outpost, outpost, outposts, deploy in outpost, deploy in aws outpost 
summary: 在 AWS 中部署Cloud Volumes ONTAP時，您可以選擇符合您的工作負載需求的預先配置系統，也可以建立自己的設定。如果您選擇自己的配置，您應該了解可用的選項。 
---
= 在 AWS 中規劃您的Cloud Volumes ONTAP配置
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在 AWS 中部署Cloud Volumes ONTAP時，您可以選擇符合您的工作負載需求的預先配置系統，也可以建立自己的設定。如果您選擇自己的配置，您應該了解可用的選項。



== 選擇Cloud Volumes ONTAP許可證

Cloud Volumes ONTAP有多種授權選項。每個選項都可以讓您選擇符合您需求的消費模式。

* link:concept-licensing.html["了解Cloud Volumes ONTAP的授權選項"]
* link:task-set-up-licensing-aws.html["了解如何設定許可"]




== 選擇支援的區域

大多數 AWS 區域都支援Cloud Volumes ONTAP 。 https://bluexp.netapp.com/cloud-volumes-global-regions["查看支援區域的完整列表"^] 。

必須先啟用較新的 AWS 區域，然後才能在這些區域中建立和管理資源。 https://docs.aws.amazon.com/general/latest/gr/rande-manage.html["AWS 文件：了解如何啟用區域"^] 。



=== 選擇受支援的本地區域

選擇本地區域是可選的。包括新加坡在內的一些 AWS 本地區域支援Cloud Volumes ONTAP 。 AWS 中的Cloud Volumes ONTAP僅支援單一可用區域中的高可用性 (HA) 模式。不支援單節點部署。


NOTE: Cloud Volumes ONTAP不支援 AWS 本地區域中的資料分層和雲端分層。此外，不支援具有未符合Cloud Volumes ONTAP資格的實例的本地區域。例如邁阿密，它不能用作本地區域，因為它只有不受支援且不合格的 Gen6 實例。

link:https://aws.amazon.com/about-aws/global-infrastructure/localzones/locations/?nc=sn&loc=3["AWS 文件：查看本地區域的完整列表"^] 。必須先啟用本地區域，然後才能在這些區域中建立和管理資源。

link:https://docs.aws.amazon.com/local-zones/latest/ug/getting-started.html["AWS 文件：AWS 本機區域入門"^] 。



== 選擇支援的實例

Cloud Volumes ONTAP支援多種執行個體類型，具體取決於您選擇的授權類型。

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-aws.html["AWS 中Cloud Volumes ONTAP支援的配置"^]



== 了解儲存限制

Cloud Volumes ONTAP系統的原始容量限制與許可證相關。額外的限制會影響聚合和磁碟區的大小。在規劃配置時您應該注意這些限制。

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limits-aws.html["AWS 中Cloud Volumes ONTAP的儲存限制"^]



== 在 AWS 中調整系統規模

調整Cloud Volumes ONTAP系統的大小可以幫助您滿足效能和容量要求。選擇實例類型、磁碟類型和磁碟大小時，您應該注意幾個關鍵點：

實例類型::
+
--
* 將您的工作負載要求與每個 EC2 執行個體類型的最大吞吐量和 IOPS 相符。
* 如果多個使用者同時向系統寫入數據，請選擇具有足夠 CPU 來管理請求的執行個體類型。
* 如果您有一個主要用於讀取的應用程序，那麼請選擇具有足夠 RAM 的系統。
+
** https://aws.amazon.com/ec2/instance-types/["AWS 文件：Amazon EC2 執行個體類型"^]
** https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html["AWS 文件：Amazon EBS 優化實例"^]




--
EBS 磁碟類型:: 從高層次來看，EBS 磁碟類型之間的差異如下。要了解有關 EBS 磁碟用例的更多信息，請參閱 http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html["AWS 文件：EBS 磁碟區類型"^]。
+
--
* _通用 SSD (gp3)_ 磁碟是成本最低的 SSD，可在廣泛的工作負載中平衡成本和效能。效能以 IOPS 和吞吐量來定義。 Cloud Cloud Volumes ONTAP 9.7 及更高版本支援 gp3 磁碟。
+
當您選擇 gp3 磁碟時， NetApp控制台會填寫預設 IOPS 和吞吐量值，這些值會根據所選磁碟大小提供與 gp2 磁碟相當的效能。您可以增加這些值以更高的成本獲得更好的效能，但我們不支援較低的值，因為這會導致效能下降。簡而言之，堅持預設值或增加它們。不要降低它們。 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html#gp3-ebs-volume-type["AWS 文件：了解有關 gp3 磁碟及其效能的更多信息"^] 。

+
請注意， Cloud Volumes ONTAP支援具有 gp3 磁碟的 Amazon EBS Elastic Volumes 功能。link:concept-aws-elastic-volumes.html["了解有關彈性卷支持的更多信息"] 。

* _通用 SSD (gp2)_ 磁碟可在廣泛的工作負載中平衡成本和效能。性能以 IOPS 來定義。
* _Provisioned IOPS SSD (io1)_ 磁碟適用於需要以較高成本獲得最高效能的關鍵應用程式。
+
請注意， Cloud Volumes ONTAP支援具有 io1 磁碟的 Amazon EBS Elastic Volumes 功能。link:concept-aws-elastic-volumes.html["了解有關彈性卷支持的更多信息"] 。

* _吞吐量最佳化 HDD (st1)_ 磁碟適用於需要以較低價格實現快速、一致吞吐量的頻繁存取的工作負載。
+

NOTE: 由於缺乏連接，AWS 本地區域無法將資料分層到 AWS S3。



--
EBS 磁碟大小:: 如果您選擇的配置不支援link:concept-aws-elastic-volumes.html["Amazon EBS 彈性卷功能"]，那麼您需要在啟動Cloud Volumes ONTAP系統時選擇初始磁碟大小。之後，您可以link:concept-storage-management.html["讓控制台為您管理系統容量"]，但如果你想link:task-create-aggregates.html["自己創建聚合"]，請注意以下事項：
+
--
* 聚合中的所有磁碟必須具有相同的大小。
* EBS 磁碟的效能與磁碟大小相關。此大小決定了 SSD 磁碟的基線 IOPS 和最大突發持續時間以及 HDD 磁碟的基線和突發吞吐量。
* 最終，您應該選擇能夠提供您所需的_持續效能_的磁碟大小。
* 即使您確實選擇了更大的磁碟（例如，六個 4 TiB 磁碟），您可能無法獲得所有的 IOPS，因為 EC2 執行個體可能會達到其頻寬限制。
+
有關 EBS 磁碟效能的更多詳細信息，請參閱 http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html["AWS 文件：EBS 磁碟區類型"^]。

+
如上所述，支援 Amazon EBS Elastic Volumes 功能的Cloud Volumes ONTAP配置不支援選擇磁碟大小。link:concept-aws-elastic-volumes.html["了解有關彈性卷支持的更多信息"] 。



--




== 查看預設系統磁碟

除了用戶資料的儲存之外，控制台還購買了Cloud Volumes ONTAP系統資料（啟動資料、根資料、核心資料和NVRAM）的雲端儲存。出於規劃目的，在部署Cloud Volumes ONTAP之前查看這些詳細資訊可能會有所幫助。

link:reference-default-configs.html#aws["查看 AWS 中Cloud Volumes ONTAP系統資料的預設磁碟"] 。


TIP: 控制台代理還需要係統磁碟。 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-connector-default-config.html["查看控制台代理預設配置的詳細信息"^] 。



== 準備在 AWS Outpost 中部署Cloud Volumes ONTAP

如果您有 AWS Outpost，則可以透過在部署過程中選擇 Outpost VPC 在該 Outpost 中部署Cloud Volumes ONTAP 。體驗與駐留在 AWS 中的任何其他 VPC 相同。請注意，您需要先在 AWS Outpost 中部署控制台代理程式。

需要指出的是，存在一些限制：

* 目前僅支援單節點Cloud Volumes ONTAP系統
* 可與Cloud Volumes ONTAP一起使用的 EC2 執行個體僅限於 Outpost 中可用的執行個體
* 目前僅支援通用 SSD（gp2）




== 收集網路資訊

在 AWS 中啟動Cloud Volumes ONTAP時，您需要指定有關 VPC 網路的詳細資訊。您可以使用工作表從管理員收集資訊。



=== 單一可用區中的單一節點或 HA 對

[cols="30,70"]
|===
| AWS 資訊 | 你的價值 


| 地區 |  


| 專有網絡 |  


| 子網 |  


| 安全群組（如果使用您自己的） |  
|===


=== 多個可用區中的 HA 對

[cols="30,70"]
|===
| AWS 資訊 | 你的價值 


| 地區 |  


| 專有網絡 |  


| 安全群組（如果使用您自己的） |  


| 節點 1 可用區 |  


| 節點 1 子網 |  


| 節點 2 可用區 |  


| 節點 2 子網 |  


| 中介可用區域 |  


| 調解器子網 |  


| 中介者的金鑰對 |  


| 叢集管理網口浮動IP位址 |  


| 節點 1 上資料的浮動 IP 位址 |  


| 節點 2 上資料的浮動 IP 位址 |  


| 浮動 IP 位址的路由表 |  
|===


== 選擇寫入速度

控制台可讓您選擇Cloud Volumes ONTAP的寫入速度設定。在選擇寫入速度之前，您應該了解正常設定和高設定之間的差異以及使用高寫入速度時的風險和建議。link:concept-write-speed.html["了解有關寫入速度的更多信息"] 。



== 選擇卷使用情況設定檔

ONTAP包含多種儲存效率功能，可減少您所需的總儲存量。在控制台中建立磁碟區時，您可以選擇啟用這些功能的設定檔或停用這些功能的設定檔。您應該了解有關這些功能的更多信息，以幫助您決定使用哪個配置文件。

NetApp儲存效率功能有以下優勢：

精簡配置:: 向主機或使用者提供比實體儲存池中實際擁有的更多的邏輯儲存。不是預先分配儲存空間，而是在寫入資料時動態地將儲存空間分配給每個磁碟區。
重複資料刪除:: 透過定位相同的資料塊並將其替換為對單一共享區塊的引用來提高效率。該技術透過消除駐留在同一磁碟區中的冗餘資料區塊來減少儲存容量需求。
壓縮:: 透過壓縮主儲存、輔助儲存和歸檔儲存磁碟區內的資料來減少儲存資料所需的實體容量。

