---
sidebar: sidebar 
permalink: task-getting-started-aws.html 
keywords: amazon web services, aws, netapp, data fabric, hybrid cloud, cloud, public cloud, networking, vpc, quick, getting started, install, installing, deploy, deploying, setup, setting up, launching, requirements, prerequisites, cloud central, get started, network, vpn, multi-cloud, tier, storage tier, data tier, vpc endpoint, endpoint, S3, subscribe, subscribing, marketplace, granting, permissions, policy, iam policy, ec2 console, ami, mediator, connectivity, internet, outbound, endpoint, connection, networks, replicating, ec2 service, policies, attach, iam user, access key, secret key, keys, sign up, cloud manager, cloud volumes ontap, cloud ontap, create, console 
summary: 請確認您已完成在 AWS 中部署 Cloud Volumes ONTAP 的所有先決條件。 
---
= AWS 中 Cloud Volumes ONTAP 的部署總覽
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
要部署 Cloud Volumes ONTAP，您首先需要了解您的 AWS 訂閱和 Cloud Volumes ONTAP 授權。您也必須確認已為您的 AWS 帳戶建立 NetApp Console 代理程式。本主題中的許多資訊需要在開始部署 Cloud Volumes ONTAP 之前，作為 Console 設定的一部分完成。

您可以使用 AWS Marketplace 或 NetApp Console 在 AWS 中就職 Cloud Volumes ONTAP。下表提供在 AWS 中部署 Cloud Volumes ONTAP 所需完成之任務的高階總覽。從 AWS Marketplace 就職是一種簡化的體驗，可自動執行 Console 代理程式部署與訂閱關聯。如需從 AWS Marketplace 就職的相關資訊，請參閱 link:task-onboard-cvo-aws-marketplace.html["在 AWS Marketplace 就職 Cloud Volumes ONTAP"]。

[cols="20,35,25,25"]
|===
| 任務 | 描述 | 參考 | 私有模式部署注意事項 


 a| 
建立 Console 代理程式
 a| 
如果您還沒有 Console 代理程式，請在部署 Cloud Volumes ONTAP 之前建立一個。如果部署在沒有網際網路存取的子網路中，請手動安裝 Console 代理程式並存取在該代理程式上執行的 NetApp Console。
 a| 
請參閱 Console 設定指南：https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-aws.html["在 AWS 中建立 Console 代理程式"^]
 a| 
如果部署在無法存取網際網路的子網路中，請手動安裝 Console 代理程式，並存取在該 Console 代理程式上執行的 NetApp Console 使用者介面。請參閱 Console 設定指南：https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["在無網際網路存取的情況下手動安裝 Console 代理程式"^]



 a| 
規劃您的配置
 a| 
控制台提供符合您的工作負載要求的預先配置包，或者您可以建立自己的配置。如果您選擇自己的配置，您應該了解可用的選項。
 a| 
link:task-planning-your-config.html["規劃您的配置"]
 a| 
對於私有環境模式部署，您也需要考慮類似的規劃因素。



 a| 
設定網路
 a| 
. 確保您的 VPC 和子網路支援 Console 代理程式和 Cloud Volumes ONTAP 之間的連線。
. 啟用 AutoSupport 的傳出網際網路存取。
. 設定指向 Amazon S3 的 VPC 終端節點以實現資料分層。如果您想將 Cloud Volumes ONTAP 中的冷資料分層至低成本物件儲存，則需要 VPC 終端節點。

 a| 
link:reference-networking-aws.html["AWS 的網路需求"]
 a| 
不需要 AutoSupport 的傳出網際網路存取。其他所有連網要求保持不變。



 a| 
設定 AWS KMS
 a| 
如果您要將 Amazon 加密與 Cloud Volumes ONTAP 一起使用，請確保存在有效的客戶主金鑰 （CMK），並修改金鑰原則，將 Console 代理程式的 IAM 角色新增為金鑰使用者。
 a| 
link:task-setting-up-kms.html["設定 AWS KMS"]
 a| 
類似的步驟也適用於私有模式部署。



 a| 
從 Console 部署 Cloud Volumes ONTAP
 a| 
完成所有先決條件後，即可依照精靈中的步驟在 AWS 中部署 Cloud Volumes ONTAP。
 a| 
* link:task-quick-deploy-aws.html["使用快速建立部署 Cloud Volumes ONTAP"]
* link:task-deploying-otc-aws.html["使用進階選項部署 Cloud Volumes ONTAP"]

 a| 
在開始部署之前，請確保您已從 NetApp 購買 Cloud Volumes ONTAP 授權。私有模式部署需要基於節點的 BYOL 授權。不支援使用 Marketplace 訂閱來支付 Cloud Volumes ONTAP 的使用費用。請從 NetApp 取得授權檔案，並在部署期間上傳。請參閱：

* link:concept-license-management.html["基於節點的 BYOL 授權管理"]
* link:task-manage-node-licenses.html["管理節點型 BYOL 授權"]
* link:task-quick-deploy-aws.html["使用快速建立部署 Cloud Volumes ONTAP"]
* link:task-deploying-otc-aws.html["使用進階選項部署 Cloud Volumes ONTAP"]


|===
.相關連結
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-bluexp.html["為 AWS 建立控制台代理"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-marketplace.html["從 AWS Marketplace 建立控制台代理"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["在本機安裝並設定控制台代理"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-aws.html["控制台代理的 AWS 權限"^]

