---
sidebar: sidebar 
permalink: task-convert-node-capacity.html 
keywords: license conversion, convert node-based to capacity based, by-node to by-capacity, license conversion for node based, BlueXP, Console 
summary: '在基於節點的許可證的可用性終止 (EOA) 之後，您應該使用許可證轉換工具過渡到基於容量的許可證。' 
---
= 將Cloud Volumes ONTAP基於節點的許可證轉換為基於容量的許可證
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在基於節點的許可證的可用性終止 (EOA) 之後，您應該使用NetApp Console中的許可證轉換工具過渡到基於容量的許可證。

對於年度或長期承諾， NetApp建議您在 EOA 日期（2024 年 11 月 11 日）或許可證到期日之前聯繫您的NetApp代表，以確保過渡的先決條件到位。如果您沒有Cloud Volumes ONTAP節點的長期合同，並且根據按需付費 (PAYGO) 訂閱運行您的系統，那麼在 2024 年 12 月 31 日支援終止 (EOS) 之前規劃您的轉換非常重要。在這兩種情況下，您都應確保您的系統符合要求，然後再使用NetApp Console中的許可證轉換工具實現無縫過渡。

有關 EOA 和 EOS 的信息，請參閱link:concept-licensing.html#end-of-availability-of-node-based-licenses["基於節點的許可證的可用性終止"]。

NetApp 已限制 BYOL 授權的購買、延期和續約。如需詳細資訊，請參閱 https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html#restricted-availability-of-byol-licensing-for-cloud-volumes-ontap["Cloud Volumes ONTAP的 BYOL 授權可用性受限"^]。



[[conversion-in-a-standard-mode-deployment]]
== 標準模式部署中的轉換

如果您採用標準模式部署，可以使用 NetApp Console 中的授權轉換工具，將節點型授權轉換為容量型授權。所有雲端供應商（包括 AWS、Azure 和 Google Cloud）均支援此轉換。您可以將節點型授權轉換為透過市場購買的任何容量型授權。例如，如果您擁有 PAYGO 標準版節點型授權，則可以將其轉換為透過市場購買的任何容量型授權。

.關於此任務
* 當您使用許可證轉換工具時，從基於節點到基於容量的許可模型的轉換是在現場線上進行的，從而無需進行任何資料遷移或配置額外的雲端資源。
* 這是一項不中斷營運的操作：
+
** 服務不會中斷，也不會發生應用程式停機時間。
** Cloud Volumes ONTAP系統中的帳戶和應用程式資料保持不變。
** 轉換後，底層雲端資源不受影響。


* 許可證轉換工具支援所有部署類型，例如單節點、單可用區 (AZ) 中的高可用性 (HA)、多 AZ 中的 HA、自帶許可證 (BYOL) 和 PAYGO。
* 在標準模式下，此工具支援所有節點型授權作為來源，以及所有容量型授權作為目的地。例如，如果您擁有 BYOL 節點型授權，您可以將其轉換為從 NetApp 購買的任何容量型授權。
* 轉換完成後，節點型授權的序號將替換為容量型格式。此操作是轉換過程的一部分，並會反映在您的 NetApp 支援網站 （NSS） 帳戶中。
* 當您過渡到基於容量的模型時，您的資料將繼續保留在與基於節點的許可相同的位置。這種方法保證了資料放置不會中斷，並在整個過渡過程中堅持資料主權原則。


.開始之前
* 您應該擁有一個具有客戶存取權限或管理員存取權限的 NSS 帳戶。
+
** 您的 NSS 帳戶應使用您用於存取控制台的使用者憑證進行註冊。
** Cloud Volumes ONTAP系統應連結至具有客戶存取權限或管理員存取權限的 NSS 帳戶。


* 您應該擁有有效的基於容量的許可證，可以是 BYOL 許可證或市場訂閱。
* 您的帳戶中應該有基於容量的許可證。此授權可以是市場訂閱，也可以是控制台中 *Licenses and subscriptions* 下提供的 BYOL/私人優惠包。
* 在選擇目的地套餐之前，請先了解以下標準：
+
** 如果帳戶具有基於容量的 BYOL 許可證，則所選目標包應與帳戶的 BYOL 基於容量的許可證保持一致：
+
*** 什麼時候 `Professional`被選為目標包，該帳戶應具有帶有專業包的 BYOL 許可證：
*** 什麼時候 `Essentials`被選為目標包，該帳戶應具有 Essentials 包的 BYOL 授權。


** 如果目標套件與帳戶的 BYOL 授權可用性不一致，則表示基於容量的授權可能不包含所選套件。在這種情況下，我們將透過您的市場訂閱向您收費。
** 如果沒有基於容量的 BYOL 授權而只有市場訂閱，則應確保所選包包含在基於容量的市場訂閱中。
** 如果您現有的基於容量的許可證中沒有足夠的容量，並且您有市場訂閱來對額外的容量使用收費，那麼您將透過市場訂閱為額外的容量付費。
** 如果您現有的基於容量的許可證中沒有足夠的容量，並且您沒有市場訂閱來收取額外容量使用的費用，則無法進行轉換。您應該添加市場訂閱來收取額外容量或將可用容量擴展到您目前的授權。
** 如果目標套件與帳戶的 BYOL 授權可用性不一致，且您現有的基於容量的授權中沒有足夠的容量，那麼您將透過市場訂閱付費。





NOTE: 如果任何一項要求未滿足，則許可證轉換不會發生。在特定情況下，許可證可能會轉換，但不能使用。點擊資訊圖示以識別問題並採取糾正措施。

.步驟
. 從左側導覽功能表中，選擇“儲存”>“管理”。
. 在「*系統*」頁面上，雙擊要修改許可證類型的系統的名稱。
. 在「概覽」標籤上，按一下「功能」面板。
. 檢查*充電方式*旁邊的鉛筆圖示。如果您的系統的充電方式是 `Node Based`，可轉換為按容量充電。
+

TIP: 如果您的Cloud Volumes ONTAP系統已按容量收費，或任何要求未滿足，則該圖示將被停用。

. 在*將基於節點的許可證轉換為基於容量的許可證*螢幕上，驗證系統名稱和來源許可證詳細資訊。
. 選擇轉換現有許可證的目標包：
+
** 必需品。預設值為 `Essentials`。
** 專業的


. 如果您擁有 BYOL 許可證，則可以在轉換完成後選取核取方塊以從控制台中刪除基於節點的許可證。如果轉換仍在進行中，選取此核取方塊將不會從控制台中刪除授權。此選項不適用於市場訂閱。
. 選取核取方塊以確認您了解變更的含義，然後按一下「*繼續*」。


.完成後
查看新的授權序號，並在 Console 的「管理 > Licenses and subscriptions」功能表中驗證變更。



[[conversion-in-a-private-mode-deployment]]
== 私有模式部署中的轉換

如果您採用私有模式部署，可以使用 NetApp Console 中的授權轉換工具，將節點型授權轉換為容量型授權。所有雲端供應商，包括 AWS、Azure 和 Google Cloud，均支援此轉換。

由於私有模式不支援市場訂閱，您需要從 NetApp 購買 Essentials （自帶授權 (BYOL)）套件。這樣，您就可以在 BYOL 模式下享受容量型授權的優勢，而無需市場訂閱。


NOTE: 在私有模式下，不支援將基於節點的授權轉換為除 Essentials 之外的任何基於容量的授權。

.關於此任務
* 轉換後，您節點型授權的全部容量將在 Essentials 套件下進行追蹤，您仍將依照 BYOL 協議計費。
* 使用授權轉換工具時，從節點型授權模式到容量型授權模式的轉換將直接就地完成，無需任何資料移轉或額外雲端資源的佈建。
* 這是一項不中斷營運的操作：
+
** 服務不會中斷，也不會發生應用程式停機時間。
** Cloud Volumes ONTAP系統中的帳戶和應用程式資料保持不變。
** 轉換後，底層雲端資源不受影響。
** 您的資料將繼續保留在與節點型授權相同的位置。這種方法可確保資料放置不會中斷，並在整個過渡過程中維護資料主權原則。


* 授權轉換工具支援所有部署類型，例如單一節點和單一可用度區域 （AZ） 中的高可用度 （HA） 組態以及多個 AZ 組態。
* 轉換完成後，Cloud Volumes ONTAP 系統將更新新的序號。


.開始之前
* 由於私有模式 Cloud Volumes ONTAP 部署不支援市場訂閱，因此您必須從 NetApp 取得基於容量的 Essentials 授權。
* 容量型授權的容量應與節點型授權的容量相近，以便進行轉換。
* 基於容量的 Essentials 套件應與您的基於節點的 BYOL 授權類型相對應。例如，採用次要 Volume （HA） 的私有雲模式部署應使用對應的 Essentials Secondary HA 授權，或使用最符合的授權，例如 Essentials Primary 或 Essentials Primary HA。


.步驟
. 從左側導覽功能表中，選擇“儲存”>“管理”。
. 在「*系統*」頁面上，雙擊要修改許可證類型的系統的名稱。
. 在「概覽」標籤上，按一下「功能」面板。
. 請查看 *Charging method* 旁的鉛筆圖示。如果您系統的收費方式為 `Node Based`，您可以將其轉換為容量型授權。
+

TIP: 如果您的Cloud Volumes ONTAP系統已按容量收費，或任何要求未滿足，則該圖示將被停用。

. 在*將基於節點的許可證轉換為基於容量的許可證*螢幕上，驗證系統名稱和來源許可證詳細資訊。
. 選擇 Essentials 作為轉換現有授權的目的地套件：
. 轉換完成後，您可以選取此核取方塊，從 Console 中刪除節點型授權。如果轉換仍在進行中，選取此核取方塊不會從 Console 中移除授權。
. 選取核取方塊以確認您了解變更的含義，然後按一下「*繼續*」。


.完成後
查看新的授權序號，並在 Console 的「管理 > Licenses and subscriptions」功能表中驗證變更。



[[pricing-in-different-hyperscalars]]
== 不同超標量中的定價

有關定價的詳細信息，請訪問 https://bluexp.netapp.com/pricing/["NetApp Console網站"^]。

有關特定超標量中的私人優惠的信息，請寫信至：

* AWS - awspo@netapp.com
* Azure - azurepo@netapp.com
* Google Cloud - gcppo@netapp.com


.相關連結
* link:concept-licensing.html["Cloud Volumes ONTAP許可"]
* link:task-manage-capacity-licenses.html["管理Cloud Volumes ONTAP基於容量的許可"]
* link:task-manage-node-licenses.html["管理節點型授權"]

