---
sidebar: sidebar 
permalink: task-verify-autosupport.html 
keywords: autosupport, set up autosupport, test autosupport, asup, test asup 
summary: AutoSupport主動監控系統的健康狀況並向NetApp技術支援發送訊息。預設情況下，每個節點上都啟用AutoSupport ，以使用 HTTPS 傳輸協定向技術支援發送訊息。最好驗證AutoSupport是否可以發送這些訊息。 
---
= 驗證Cloud Volumes ONTAP 的AutoSupport設置
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AutoSupport主動監控系統的健康狀況並向NetApp技術支援發送訊息。預設情況下，每個節點上都啟用AutoSupport ，以使用 HTTPS 傳輸協定向技術支援發送訊息。最好驗證AutoSupport是否可以發送這些訊息。

唯一需要的設定步驟是確保Cloud Volumes ONTAP具有外部網路連線。有關詳細信息，請參閱您的雲端提供者的網路要求。



== AutoSupport要求

Cloud Volumes ONTAP節點需要NetApp AutoSupport的出站互聯網存取權限，它可以主動監控系統的健康狀況並向NetApp技術支援發送訊息。

路由和防火牆策略必須允許 HTTPS 流量到達下列端點，以便Cloud Volumes ONTAP可以傳送AutoSupport訊息：

* \ https://mysupport.netapp.com/aods/asupmessage
* \ https://mysupport.netapp.com/asupprod/post/1.0/postAsup


如果沒有可用的出站網路連線來傳送AutoSupport訊息， NetApp Console會自動設定您的Cloud Volumes ONTAP系統以使用控制台代理程式作為代理伺服器。唯一的要求是確保控制台代理的安全群組允許透過連接埠 3128 進行入站連線。部署控制台代理程式後，您需要開啟此連接埠。

如果您為Cloud Volumes ONTAP定義了嚴格的出站規則，那麼您還需要確保Cloud Volumes ONTAP安全群組允許透過連接埠 3128 進行出站連線。


TIP: 如果您使用 HA 對，則 HA 中介不需要外部網路存取。

驗證出站網路存取可用後，您可以測試AutoSupport以確保它可以發送訊息。有關說明，請參閱 https://docs.netapp.com/us-en/ontap/system-admin/setup-autosupport-task.html["ONTAP文檔：設定AutoSupport"^]。



== 排除AutoSupport配置故障

如果出站連線不可用，且控制台無法設定您的Cloud Volumes ONTAP系統以使用控制台代理程式作為代理伺服器，您將收到來自控制台的通知，提示您的系統無法傳送AutoSupport訊息。請依照以下步驟解決此問題。

.步驟
. 使用 SSH 安全地連接到Cloud Volumes ONTAP系統，以使用ONTAP CLI。
+
link:task-connecting-to-otc.html["了解如何透過 SSH 連線到Cloud Volumes ONTAP"] 。

. 查看AutoSupport子系統的詳細狀態：
+
`autosupport check show-details`

+
回覆內容如下：

+
[listing]
----
    Category: smtp
          Component: mail-server
             Status: failed
             Detail: SMTP connectivity check failed for destination:
                     mailhost. Error: Could not resolve host - 'mailhost'
            Corrective Action: Check the hostname of the SMTP server

    Category: http-https
        Component: http-put-destination
            Status: ok
            Detail: Successfully connected to:
                    <https://support.netapp.com/put/AsupPut/>.

          Component: http-post-destination
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/asupprod/post/1.0/postAsup.

    Category: on-demand
          Component: ondemand-server
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/aods/asupmessage.

    Category: configuration
            Component: configuration
                Status: ok
                Detail: No configuration issues found.
    5 entries were displayed.
----
+
如果 http-https 類別的狀態是 `OK` 這表示AutoSupport已正確配置，可以發送訊息。

. 否則，請驗證每個Cloud Volumes ONTAP節點的代理 URL：
+
`autosupport show -fields proxy-url`

. 如果代理 URL 參數為空，請設定Cloud Volumes ONTAP以使用控制台代理作為代理：
+
`autosupport modify -proxy-url \http://<console agent private ip>:3128`

. 再次確認AutoSupport狀態：
+
`autosupport check show-details`

. 如果狀態仍然失敗，請驗證Cloud Volumes ONTAP和控制台代理之間是否透過連接埠建立連線。 `3128`。
. 如果驗證後狀態仍然失敗，請透過 SSH 連線至控制台代理程式。
+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-maintain-connectors.html#connect-to-the-linux-vm["了解有關控制台代理連接到 Linux VM 的更多信息"^]

. 前往 `/opt/application/netapp/cloudmanager/docker_occm/data/`。
. 開啟代理設定檔 `squid.conf`。這是文件的結構：
+
[listing]
----
        http_port 3128
        acl netapp_support dst support.netapp.com
        http_access allow netapp_support
        request_header_max_size 21 KB
        reply_header_max_size 21 KB
        http_access deny all
        httpd_suppress_version_string on
----
. 如果您的檔案中沒有Cloud Volumes ONTAP系統的 CIDR 區塊條目，請新增條目並允許存取：
+
`acl cvonet src <cidr>`

+
`http_access allow cvonet`

+
以下是一個例子：

+
[listing]
----
        http_port 3128
        acl netapp_support dst support.netapp.com
        acl cvonet src <cidr>
        http_access allow netapp_support
        http_access allow cvonet
        request_header_max_size 21 KB
        reply_header_max_size 21 KB
        http_access deny all
        httpd_suppress_version_string on

----
. 編輯設定檔後，重啟代理容器。 `sudo`。然後，根據您使用的是 Docker 還是 Podman，執行以下命令：
+
對於 Docker，請運行 `docker restart squid`。

+
如果您使用的是 Podman，請執行 `podman restart squid`。

. 傳回ONTAP CLI 並驗證Cloud Volumes ONTAP是否可以傳送AutoSupport訊息：
+
`autosupport check show-details`



.相關連結
* link:reference-networking-aws.html["AWS 中Cloud Volumes ONTAP的網路需求"^]
* link:reference-networking-azure.html["Azure 中Cloud Volumes ONTAP的網路需求"^]
* link:reference-networking-gcp.html["Google Cloud 中Cloud Volumes ONTAP的網路需求"^]

