= AWS 中 Cloud Volumes ONTAP 和資料服務的彈性計費
:allow-uri-read: 




=== AWS 中 Cloud Volumes ONTAP 和資料服務的彈性計費

NetApp 在 AWS 中為您的 Cloud Volumes ONTAP 訂閱提供了更進階的計費選項，讓您能更靈活地控制 Cloud Volumes ONTAP 容量與 NetApp 資料服務（例如 NetApp Backup and Recovery）的付款方式。過去，所有 Cloud Volumes ONTAP 及資料服務的使用情形，都是透過 AWS marketplace 中的 NetApp Intelligent Services（NIS）條目一起計費。

由於 AWS 企業折扣方案（EDP）的變更，NetApp 在 AWS Marketplace 中推出了獨立的 Cloud Volumes ONTAP 訂閱，讓您可以將 Cloud Volumes ONTAP 容量的計費與資料服務的計費分開。這種分離方式讓您更靈活地管理 EDP 抵扣額度和成本。NetApp 建議您使用獨立訂閱來更好地管理 Cloud Volumes ONTAP 的使用成本，同時在 2026 年 7 月 31 日 EDP 要求生效後，繼續使用 NIS 訂閱來支付資料服務的計費。

AWS 中的獨立 Cloud Volumes ONTAP 訂閱僅支援有效的基於容量的 Essentials 或 Freemium 許可套餐。Professional 套餐不支援。您可以選擇最適合您需求的計費方式：

* *獨立 Cloud Volumes ONTAP 訂閱（建議）*：您可以透過 AWS Marketplace 中的獨立訂閱支付 Cloud Volumes ONTAP 的使用費用，同時繼續透過 NIS 訂閱支付資料服務費用。對於大多數在 NetApp Console 中同時擁有獨立訂閱和 NIS 訂閱並與其 AWS 帳戶相關聯的客戶，這是建議的選擇。
* *合併 NIS 訂閱*：透過現有的 NIS 清單同時支付 Cloud Volumes ONTAP 和資料服務的費用。此合併方案適用於在 NetApp Console 中僅關聯了 NIS 訂閱的現有客戶。但是，NetApp 建議您設定 Cloud Volumes ONTAP 使用量的計費偏好設定，並切換到獨立訂閱，以便更好地管理成本。


根據您的訂閱類型，您將遇到以下情況：

.僅限獨立訂閱（新客戶）
如果您在 NetApp Console 中僅擁有與您的 AWS 帳戶關聯的獨立 AWS 訂閱，而沒有 NIS 訂閱，則在部署期間只能選擇 Essentials 授權包。資料服務的 *Backup and Recovery* 選項對您不可用。

.獨立訂閱和 NIS 訂閱（現有客戶）
如果您的 AWS 帳戶同時關聯了 NIS 和獨立訂閱，且您尚未透過 NetApp Console 中的 *Billing preferences* 標籤設定帳單首選項，則 Cloud Volumes ONTAP 的使用量預設仍透過 NIS 計費。對於執行 Professional 套餐的任何 Cloud Volumes ONTAP 執行個體，這也是預設設置，因為獨立清單不支援 Professional。您可以設定帳單首選項並選擇每項服務的計費方式：

* 將獨立訂閱設定為 Cloud Volumes ONTAP（包含 Essentials 套餐）的首選計費帳戶。如果您只有 Professional 套餐，可以將其轉換為 Essentials 套餐，並透過設定計費首選項來收取 Cloud Volumes ONTAP 的使用費用。我們推薦這種方法，因為它有助於您更有效地管理 Cloud Volumes ONTAP EDP 積分。
* 使用 NIS 訂閱進行資料服務計費，或透過 Professional 套餐計費 Cloud Volumes ONTAP 使用量。在部署期間，啟用 *Backup and Recovery* 資料服務，並選擇 Professional 授權套餐，以透過 NIS 訂閱計費資料服務。


.僅限 NIS 訂閱用戶（現有客戶）
如果您是已擁有與 AWS 帳戶關聯的 NIS 訂閱的現有客戶，則此說明適用。您可以繼續像現在一樣同時對 Cloud Volumes ONTAP 和資料服務進行計費。但是，NetApp 建議您切換到獨立訂閱模式，以便更好地管理 Cloud Volumes ONTAP 的使用成本：

* 在 AWS 入口網站上訂閱新的獨立清單。
* 將獨立訂閱連結至您的 AWS 帳戶。
* 將您的計費偏好設定為使用 Essentials 套餐的 Cloud Volumes ONTAP 獨立訂閱。
* （如適用）將您的 Professional 套件轉換為 Essentials 套件，並設定計費偏好設定。
* 繼續透過您的 NIS 訂閱進行資料服務計費。



NOTE: 使用多種訂閱類型或在清單之間遷移時，不會發生重複計量。

.相關連結
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-set-up-licensing-aws.html["在 AWS 中設定Cloud Volumes ONTAP許可"^]
* https://docs.netapp.com/us-en/console-licenses-subscriptions/task-manage-capacity-licenses.html#change-charging-methods["變更容量授權的收費方式"^]

