= Cloud Volumes ONTAP 9.19.1 RC
:allow-uri-read: 




[[cloud-volumes-ontap-9-19-1-rc]]
=== Cloud Volumes ONTAP 9.19.1 RC

現在您可以使用 NetApp Console 在 Google Cloud 中部署和管理 Cloud Volumes ONTAP 9.19.1 的候選發行版本 （RC）。此版本尚不支援在 Amazon Web Services （AWS） 和 Microsoft Azure （Azure） 中部署和升級。

link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/["了解有關此版本Cloud Volumes ONTAP的更多信息"^] 。



[[support-for-next-generation-google-cloud-vms-in-cloud-volumes-ontap-ha]]
=== Cloud Volumes ONTAP HA 支援下一代 Google Cloud VM

在 9.19.1 版本中，NetApp 將 Cloud Volumes ONTAP 高可用性 （HA） 部署從 N2 VM 移轉至下一代 Google Cloud C3 系列 VM，以提供更快速且更具擴充性的體驗。


NOTE: 此支援僅適用於單可用區 (AZ) HA 部署。

現在，您可以在 Google Cloud 中部署 Cloud Volumes ONTAP 9.19.1 及更高版本時，充分利用 C3 系列虛擬機器。這些虛擬機器效能更佳，容量上限更高。它們採用 Google Virtual NIC （gVNIC） 和 Hyperdisk Balanced 磁碟，可在密集型工作負載下提供動態效能。

如果您的 Cloud Volumes ONTAP 系統執行的是 9.19.1 或更新版本，則用於在單一 AZ 中輕鬆部署的預先設定套件會自動使用 C3 VM，同時可讓您根據工作負載需求自訂 IOPS 和處理量參數。同樣地，在建立集合體時，您可以新增 Zonal Hyperdisk Balanced 磁碟，以在 Google Cloud 中實現更佳的效能和擴充性。您也可以選擇 C3 系列機器的 LSSD 變體，以獲得預設的 Flash Cache 支援。

請注意以下幾點：

* 在 Cloud Volumes ONTAP 部署中，您無法將 C3 VM 變更為 N2 系列 VM，反之亦然。但是，您可以在 C3 系列的不同變體之間切換執行個體類型。
+

NOTE: 根據所連接的資料磁碟數量，在 C3 系列實例中變更實例類型可能需要更長時間。請事先規劃配置，以避免影響效能。

* 變更執行個體類型時，如果您選擇 c3-standard-44 或 c3-standard-88 及其本機 SSD （LSSD） 變體作為目標 VM，則會自動套用 Google 網路服務輸出網路層 _Tier-1_。如果您切換回任何其他 C3 變體，則輸出網路層將設定為 _Standard_。
+

NOTE: 將出口網路層級變更為 _Tier-1_ 會產生額外費用。請據此規劃部署和升級。

* 如果選擇 C3 的 LSSD 變體，則預設會啟用 Flash Cache。即使目標變體支援 Flash Cache，您也無法在 Cloud Volumes ONTAP 部署中切換 C3 LSSD 變體。
* 在 C3 VM 上，您可以為新的聚合和現有的聚合新增磁碟區。
* 將 N2 VM 類型的 Cloud Volumes ONTAP 系統複製到 C3 VM 類型時，磁碟類型預設為 Hyperdisk Balanced。
* 您可以透過 NetApp Console 或使用 `PUT /gcp/ha/aggregates/{workingEnvironmentId}/{aggregateName}` API 在新增聚合時變更 IOPS 和吞吐量設定。


https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Google Cloud 中 Cloud Volumes ONTAP 支援的組態"^]

https://docs.cloud.google.com/compute/docs/general-purpose-machines#c3_series["Google 文件：C3 機器系列"^]



[[simplified-cloud-volumes-ontap-deployment-in-google-cloud]]
=== 簡化 Google Cloud 中的 Cloud Volumes ONTAP 部署

現在，您可以使用 *Quick create* 精靈在 Google Cloud 中部署 Cloud Volumes ONTAP，支援單一節點和高可用性 (HA) 配置。此簡化流程減少了步驟，在單一頁面上自動設定預設值，並將導覽步驟降至最少，從而實現更快、更輕鬆的部署。

.相關連結
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-quick-deploy-gcp.html["使用 Quick create 在 Google Cloud 中部署 Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-deploying-gcp.html["使用 Google Cloud 中的進階選項部署 Cloud Volumes ONTAP"^]




[[introducing-access-roles-for-cloud-volumes-ontap]]
=== 為 Cloud Volumes ONTAP 引入存取角色

NetApp 為 Cloud Volumes ONTAP 引入身分與存取管理 （IAM） 角色，從而實現基於角色的存取控制 （RBAC），以提高安全性並簡化合規性。使用者仍可使用現有憑證登入 NetApp Console 執行 Cloud Volumes ONTAP 操作。但是，驗證現在透過身分聯合進行路由，使 Console 管理員能夠對這些功能進行更精細的控制。每個使用者必須擁有以下角色之一，才能對 Cloud Volumes ONTAP 執行任何操作。若無角色，使用者將無法檢視或存取 Cloud Volumes ONTAP 執行個體。

* *Cloud Volumes ONTAP viewer*：授予對 Cloud Volumes ONTAP 畫面和索引標籤的唯讀存取權限。在此角色中，某些畫面和操作按鈕將被停用。
* *Cloud Volumes ONTAP operator*：支援日常管理任務，例如新增磁碟區、管理儲存和設定複製。
* *Cloud Volumes ONTAP admin*：提供對所有 Cloud Volumes ONTAP 操作的完全存取。


Console 管理員可透過「管理 > 身分」為 Cloud Volumes ONTAP 使用者指派角色。角色權限是基於使用者所在的組織，並套用於該組織中的所有 Cloud Volumes ONTAP 系統。

Cloud Volumes ONTAP 使用本機快取來強制執行角色型存取控制 （RBAC），該快取記錄每個使用者的權限，並每小時自動重新整理一次。當使用者被指派新角色或現有角色發生變更時，變更可能需要長達一個小時才能生效，生效後，所有角色允許的工作流程都將啟用。


NOTE: 首次部署 Console 代理程式或將現有 Console 代理程式升級至 Console 4.9.0 或更高版本時，系統會執行一次性初始化過程，自動為組織中的所有現有使用者指派 Cloud Volumes ONTAP 角色。此過程可能需要長達 30 分鐘才能完成。完成後，Console 會將對應的角色指派給現有使用者。

Cloud Volumes ONTAP 角色適用於 Amazon Web Service (AWS)、Microsoft Azure (Azure) 和 Google Cloud 環境。

.相關連結
* https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["NetApp Console 存取角色"^]
* https://docs.netapp.com/us-en/console-setup-admin/reference-iam-cvo-roles.html["NetApp Console 中的 Cloud Volumes ONTAP 存取角色"^]

